name: Unit Test CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set Up Node'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Test
        run: yarn test:coverage
        continue-on-error: true

      - name: Report code coverage
        uses: ChicagoFlutter/lcov-cop@v1.0.2
        with:
          path: './test-coverage/lcov.info'
          min_coverage: 100

      - uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: test-coverage/*
          retention-days: 1
