name: Unit Test CI

on: [push]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: 'Set Up Node'
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install packages
              run: yarn install

            - name: Test
              run: yarn test
              env:
                  CI: true
