name: Unit Test CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set Up Node'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn --frozen-lock-file --prefer-offline

      - name: Test
        run: yarn test:coverage
        continue-on-error: true

      - name: Record code coverage
        id: record_code_coverage
        run: |
          output="$(npx coverage-percentage ./test-coverage/lcov.info --lcov)"
          output=$(printf '%.f' $output)
          echo "::set-output name=percentage::$output"
          echo "Current test coverage is $output%"

      - name: Check test coverage
        uses: terencetcf/github-actions-lcov-minimum-coverage-checker@v1.2.0
        with:
          coverage-file: test-coverage/lcov.info
          minimum-coverage: 90

      - uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: test-coverage/*
          retention-days: 1
