name: Unit Test CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      TEST_COVERAGE_THRESHOLD: 60

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set Up Node'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Test
        run: yarn test:coverage
        continue-on-error: true

      - name: Record code coverage
        id: record_code_coverage
        run: |
          output="$(npx coverage-percentage ./test-coverage/lcov.info --lcov)"
          echo "::set-output name=percentage::$output"

      - name: Check test coverage percentage
        if: ${{ steps.record_code_coverage.outputs.percentage < env.TEST_COVERAGE_THRESHOLD }}
        run: |
          echo "Test coverage percentage is ${{ steps.record_code_coverage.outputs.percentage }}%"
          echo "Test coverage must not below the minimum threshold of ${{ env.TEST_COVERAGE_THRESHOLD }}%"
          exit 1

      - uses: actions/upload-artifact@v2
        with:
          name: test-coverage-report
          path: test-coverage/*
          retention-days: 1
